-- AlterTable
ALTER TABLE "bills" ADD COLUMN     "cgst" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "grand_total" DOUBLE PRECISION,
ADD COLUMN     "gst_rate" DOUBLE PRECISION NOT NULL DEFAULT 18,
ADD COLUMN     "gst_type" TEXT,
ADD COLUMN     "igst" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "sgst" DOUBLE PRECISION DEFAULT 0;
